// Generated by gencpp from file turtle_diff_drive/wheel_velocity.msg
// DO NOT EDIT!


#ifndef TURTLE_DIFF_DRIVE_MESSAGE_WHEEL_VELOCITY_H
#define TURTLE_DIFF_DRIVE_MESSAGE_WHEEL_VELOCITY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtle_diff_drive
{
template <class ContainerAllocator>
struct wheel_velocity_
{
  typedef wheel_velocity_<ContainerAllocator> Type;

  wheel_velocity_()
    : omega_l(0.0)
    , omega_r(0.0)  {
    }
  wheel_velocity_(const ContainerAllocator& _alloc)
    : omega_l(0.0)
    , omega_r(0.0)  {
  (void)_alloc;
    }



   typedef double _omega_l_type;
  _omega_l_type omega_l;

   typedef double _omega_r_type;
  _omega_r_type omega_r;





  typedef boost::shared_ptr< ::turtle_diff_drive::wheel_velocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle_diff_drive::wheel_velocity_<ContainerAllocator> const> ConstPtr;

}; // struct wheel_velocity_

typedef ::turtle_diff_drive::wheel_velocity_<std::allocator<void> > wheel_velocity;

typedef boost::shared_ptr< ::turtle_diff_drive::wheel_velocity > wheel_velocityPtr;
typedef boost::shared_ptr< ::turtle_diff_drive::wheel_velocity const> wheel_velocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle_diff_drive::wheel_velocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle_diff_drive::wheel_velocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtle_diff_drive::wheel_velocity_<ContainerAllocator1> & lhs, const ::turtle_diff_drive::wheel_velocity_<ContainerAllocator2> & rhs)
{
  return lhs.omega_l == rhs.omega_l &&
    lhs.omega_r == rhs.omega_r;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtle_diff_drive::wheel_velocity_<ContainerAllocator1> & lhs, const ::turtle_diff_drive::wheel_velocity_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtle_diff_drive

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtle_diff_drive::wheel_velocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_diff_drive::wheel_velocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_diff_drive::wheel_velocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_diff_drive::wheel_velocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_diff_drive::wheel_velocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_diff_drive::wheel_velocity_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle_diff_drive::wheel_velocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "060a9c3aa2e2b6228526d91e96852741";
  }

  static const char* value(const ::turtle_diff_drive::wheel_velocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x060a9c3aa2e2b622ULL;
  static const uint64_t static_value2 = 0x8526d91e96852741ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle_diff_drive::wheel_velocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle_diff_drive/wheel_velocity";
  }

  static const char* value(const ::turtle_diff_drive::wheel_velocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle_diff_drive::wheel_velocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 omega_l\n"
"float64 omega_r\n"
;
  }

  static const char* value(const ::turtle_diff_drive::wheel_velocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle_diff_drive::wheel_velocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.omega_l);
      stream.next(m.omega_r);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wheel_velocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle_diff_drive::wheel_velocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle_diff_drive::wheel_velocity_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "omega_l: ";
    Printer<double>::stream(s, indent + "  ", v.omega_l);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "omega_r: ";
    Printer<double>::stream(s, indent + "  ", v.omega_r);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_DIFF_DRIVE_MESSAGE_WHEEL_VELOCITY_H
